# Generated by Django 4.1.7 on 2023-02-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_employee_date_joined_employee_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
